openapi: 3.0.3
info:
  title: Message API
  version: 1.0.0

paths:
  /send-push:
    post:
      summary: Send a push notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                title:
                  type: string
                body:
                  type: string
              required:
                - token
                - title
                - body
      responses:
        '200':
          description: Push sent successfully
        '400':
          description: Invalid request
        '500':
          description: Failed to send push
  /schedule-push:
    post:
      summary: Schedule a push notification for future delivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Device token for the recipient
                title:
                  type: string
                  description: Title of the push notification
                body:
                  type: string
                  description: Body of the push notification
                send_at:
                  type: string
                  format: date-time
                  description: Scheduled time for sending the push notification (ISO 8601 format)
              required:
                - token
                - title
                - body
                - send_at
      responses:
        '200':
          description: Push scheduled successfully
        '400':
          description: Invalid request
        '500':
          description: Failed to schedule push
components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
        text:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - text
        - created_at
